[project]
name = "spatial-mapping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "nbformat>=5.10.4",
    "numpy>=2.2.5",
    "plotly>=6.0.1",
    "polars>=1.29.0",
    "tqdm>=4.67.1",
]
